### ISSUE TITLE
DirectRaterLimiter::check_all does not error on exceeded cap

### ISSUE THREAD

**Issue by jean-airoldie** [antifuchs/governor#11]
If I correctly understand the `DirectRateLimiter::check_all` doc, it should error when a `n` greater than the initial `max_burst` when creating the `Quota` is passed. However it is not the case:

```rust
#[test]
fn errors_on_exceeded_cap() {
    let lim = RateLimiter::direct(Quota::per_second(nonzero!(10u32)));

    // This does not error even though we exceed the capacity.
    block_on(lim.check(nonzero!(11u32))).unwrap_err();
}
```

**Comment by antifuchs** [comment]
Thanks for reporting this issue (and for including a test case - that's really helpful)! I had to adjust it a bit so it would compile & then error:

```rust
#[test]
fn errors_on_exceeded_cap() {
    let lim = RateLimiter::direct(Quota::per_second(nonzero!(10u32)));

    // This does not error even though we exceed the capacity.
    assert_eq!(
        Err(NegativeMultiDecision::InsufficientCapacity(10)),
        lim.check_all(nonzero!(11u32))
    );
}
```

I guess we're seeing an off-by-one error somewhere!

**Comment by antifuchs** [comment]
Yeppppp, this is definitely an off-by-one error in the `weight > tau` check in `test_n_all_and_update`. I'll think about this some more.
