### ISSUE TITLE
Any reason for MonotomicClock to be an empty tuple struct?

### ISSUE THREAD

**Issue by Restioson** [antifuchs/governor#19]
Hi, I'm wondering if there's a reason that `struct MonotonicClock()` is defined as such rather than just `struct MonotonicClock`. It's extremely, terribly minor, but the second is generally considered better style AFAIK.

EDIT: typo'd second example

**Comment by antifuchs** [comment]
Thanks for raising this - always up to improve my rusty style! 

Unfortunately, I am missing something here, what's the difference between the two things you mention?

**Comment by Restioson** [comment]
Functionally? Pretty much nothing - they will compile to the same thing, a ZST. They differ slightly in how they are constructed (the first being `let x = MonotonicClock();` and the second being `let x = MonotonicClock;`), and the second is considered better style AFAIK (it's a little cleaner and removes the unnecessary `()`s).

Similarly, another tiny thing: the GCRA struct is named `GCRA` rather than the preferred `Gcra`. According to the [style guide](https://doc.rust-lang.org/1.0.0/style/style/naming/README.html), acronyms are to be treated as one word (e.g `Uuid` over `UUID`) for readability when things are combined.

These are both super minor things but I just thought I'd put them here in an issue in case there were reasons for it. I can open a PR to change it if you'd like?

**Comment by antifuchs** [comment]
Sorry, no, I meant just textually. The first and the second string is you posted in that initial message are identical (:

I see now, though - dropping the parens is ok - I'll see about that.

With the GCRA/Gcra thing, it kinda predates my knowledge of this convention... (and I'm kiiinda grossed out by it, but yeah - it's better to follow convention!)

I'd happily accept a PR to fix both of these issues!

**Comment by Restioson** [comment]
> . The first and the second string is you posted in that initial message are identical (:
Oh, haha, my mistake. I'll edit it for clarity.

**Comment by Restioson** [comment]
@antifuchs #20 opened PR

**Comment by Restioson** [comment]
Sorry to bring up tiny style stuff again... but is there any reason that constructors taking a clock take `&Clock` and clone them instead of `Clock` directly? The user could just clone it before passing it in if necessary, and taking an owned clock would remove a bound AFAICT.
