### ISSUE TITLE
[SECURITY] New release needed to fix audit warnings

### ISSUE THREAD

**Issue by Elizafox** [antifuchs/governor#195]
In the current version of governor on crates.io (0.5.1), the quanta dependency version (0.9.3) depends on mach, which is abandoned.

quanta's version was bumped in 3c2dc9967ab32a233226a9d21b5c3fb61526a13c but no corresponding release has been made.

A new release should be made as this abandoned dependency is causing `cargo audit` warnings in any crate that uses governor.

**Comment by antifuchs** [comment]
Thanks for the reminder! [v0.6.0](https://crates.io/crates/governor/0.6.0) is out now (there were a few breaking changes in the meantime, hence the bump).
