### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by maun** [antifuchs/governor#204]
Hi,
How is this crate licensed? 🙂

Edit: I now found the license field in Cargo.toml. A separate file would make this more obvious.

**Comment by antifuchs** [comment]
Hah, I'll admit for a moment I was wondering what you're talking about, of course this crate has a license - but then I saw there's no LICENSE file; I'll add one. Currently, the only (and canonical) place listing the license is [the governor crate's Cargo.toml file](https://github.com/antifuchs/governor/blob/master/governor/Cargo.toml#L6) - it's MIT.
