### ISSUE TITLE
smallvec/parking_lot vulnerability

### ISSUE THREAD

**Issue by FintanH** [antifuchs/governor#60]
Hey :wave: 

There was a vulnerability in `smallvec`:
* https://github.com/servo/rust-smallvec/issues/252
* https://github.com/RustSec/advisory-db/pull/552

I came across this while using `cargo deny` on our project [`radicle-link`](https://github.com/radicle-dev/radicle-link/) and there was a transitive dep from `governor` to `parking_lot`.

I created a pull-request for the `parking_lot` repo https://github.com/Amanieu/parking_lot/pull/276 and I wanted to track an issue here for updating this project with the fixed version too.

Hope that works for you, and let me know if I can do anything to help :v:

**Comment by antifuchs** [comment]
Thanks for filing the issue! I think we can bump the transitive dependency manually, I'll investigate.

**Comment by FintanH** [comment]
Awesome! Thanks for looking into it :)

**Comment by antifuchs** [comment]
The above PR should straighten out the deps such that a non-vulnerable version of smallvec gets used. If you have the time @FintanH, could you test with a git dependency? Otherwise, I'll time out and release v0.3.2 on the weekend.

**Comment by FintanH** [comment]
Looks good on our side :)

**Comment by antifuchs** [comment]
Released! Thanks for checking!
