### ISSUE TITLE
Observe current rate

### ISSUE THREAD

**Issue by jeromegn** [antifuchs/governor#66]
Is it possible to observe the current rate at which we're allowing cells through? I'm trying to collect metrics on the current rate for each of my rate limiters.

Currently, I'm using a separate metric to arrive at the same number (basically a prometheus counter and I'm applying a `rate` function on it, over time). I'd be surprised if these matched up perfectly. I'd rather expose the rate directly as a gauge if possible.

Looking at the code there's currently no way to determine that. I wonder if this could just work like the `check` function, but without allowing a cell. I realize this would change the code a lot because most of it appears to be using compare_exchange or other functions that mutate values.

**Comment by phayes** [comment]
I would also like this. 

I'm using this to limit the number of bad-password allowed before we temporarily lock a user's ability to login. I'd like to implement the ability for a user to see "X number of login attempts remaining", so they have some forewarning before they hit their login attempt limit.

**Comment by antifuchs** [comment]
Thanks for the input, you two! I have been thinking about how to best do this for a little bit, and I think we can get something working with an additional type parameter to support some sort of accountancy in addition to what governor does: 

The internal rate limiting representation doesn't easily let you get at general statistics like that - you can probably get the number of cells that are still available in burst capacity, but things like overall rates can't be represented in the single u64 that we keep. However! I think a trait (with a default no-op implementation of the following shape might work (completely untested, hah):

``` rust
trait RateLimitHook<K> {
  type Out = ();
  fn measurement<P: clock::Reference>(key: &K, result: Result<(), NotUntil<P>>) -> Result<Out, NotUntil>;
}
```

(I'm pretty sure this is missing one or the other affordance for one or the other use case); we could then use that in the in-memory store's `measure_and_replace_one` method under the correct conditions.

That would at least deal with the question of "what is the current rate" - you could update a prometheus per-user counter, or something similar; the question of "how many calls do you have remaining" is probably a bit more difficult to answer with that trait & will need a bit of a more involved parameter structure (and reaching into more layers of the abstraction stack), but should also be possible.

I'll try and write something up over the weekend - hopefully I'll find the time (:

**Comment by phayes** [comment]
Thanks @antifuchs!

Do you have a patreon or something similar where I could help fund the development of this feature?  (I'm specifically looking at the "query the number of cells remaining" feature).

**Comment by antifuchs** [comment]
Oooh, I do not have a Patreon, but that's a stellar idea if there is interest! I'll make a note and probably set one up in the near future (:

I've made some progress on the types involved in better observability into rate-limiting decisions (and it should be zero-ish cost too) in https://github.com/antifuchs/governor/compare/feature/middleware - this is just a snapshot & I'll need to fiddle with this some more, so stay tuned (:

**Comment by gembin** [comment]
It will be great if the `check` function can return the following information :

* The total limit of the key (max_burst + 1). This is equivalent to the common `X-RateLimit-Limit` HTTP header.
* The remaining limit of the key. Equivalent to `X-RateLimit-Remaining`.
* The number of seconds until the user should retry, and always -1 if the action was allowed. Equivalent to `Retry-After`.
* The number of seconds until the limit will reset to its maximum capacity. Equivalent to `X-RateLimit-Reset`.

**Comment by antifuchs** [comment]
The PR I mentioned above is now merged (and should have no performance impact in default usage vs. the previous release). I'd love some feedback on the API if you can - I think all of @gembin's desired information can be retrieved with the `StateInformationMiddleware` (and you could even create custom middleware that returns the correct HTTP headers as rate-limiting results).

**Comment by antifuchs** [comment]
After a long time, this has finally been released: https://crates.io/crates/governor/0.4.0
