### ISSUE TITLE
Sync rate double async rate

### ISSUE THREAD

**Issue by LAGonauta** [antifuchs/governor#68]
Hello! Thank you for this great library, it is really helpful for my [project](https://github.com/LAGonauta/RustHIDtoVPADNetworkClient) where I want to set the frequency I want to poll a controller.

However, I noticed that I was generating more data than expected with the set polling rate. I did some experimenting and noticed that my synchronous code was polling twice as fast as the expected rate. I am not quite sure if my code is wrong, but doesn't seems to be as I based it on governor's async code.

To workaround this I am halving the rate on my codebase, but that is not a proper solution and might not apply at any time...

I actually do not want to add any async runtime as a dependency to reduce binary size, so I would like to understand what is wrong. I attached to this issue a sample code and the results.

Thanks for reading, and I hope we can get this fixed :)

# Test machine

```
Kubuntu 20.04 and Windows 10 (MSYS2)
Intel Core i5-4570
```

# Expected output

```
[Async] Count: 250
[Sync] Count: 250
```

# Actual result

```
[Async] Count: 250
[Sync] Count: 500
```

# Sample Code

Cargo.toml:
```
[profile.release]
lto = true

[package]
name = "test-governor"
edition = "2018"
version = "1.0.0"

[dependencies]
governor = "0.3"
tokio = { version = "1", features = ["full"] }
```

main.rs:
```
use std::{num::NonZeroU32, thread, time::{Duration, Instant}};

use governor::{Quota, RateLimiter, clock::{self, Clock}};

#[tokio::main]
pub async fn main() {
    let polling_rate = 250; // Hz
    let sync_thread = thread::spawn(move || sync(polling_rate));

    async_(polling_rate).await;

    let _ = sync_thread.join();
}

async fn async_(polling_rate: u32) {
    let limiter = RateLimiter::direct(
        Quota::per_second(NonZeroU32::new(polling_rate)
        .unwrap())
        .allow_burst(NonZeroU32::new(1u32).unwrap())
    );

    let mut i = 0;
    let mut last = Instant::now();
    let interval = Duration::from_secs(1);
    loop {
        i = i + 1;
        let now = Instant::now();
        if now > last + interval {
            println!("[Async] Count: {}", i);
            i = 0;
            last = now;
        }

        limiter.until_ready().await;
    }
}

fn sync(polling_rate: u32) {
    let clock = clock::DefaultClock::default();
    let limiter = RateLimiter::direct_with_clock(
        Quota::per_second(NonZeroU32::new(polling_rate).unwrap())
                .allow_burst(NonZeroU32::new(1u32).unwrap()),
        &clock
    );

    let mut i = 0;
    let mut last = Instant::now();
    let interval = Duration::from_secs(1);
    loop {
        i = i + 1;
        let now = Instant::now();
        if now > last + interval {
            println!("[Sync] Count: {}", i);
            i = 0;
            last = now;
        }

        if let Err(negative) = limiter.check() {
            thread::sleep(negative.wait_time_from(clock.now()));
        }
    }
}
```

**Comment by antifuchs** [comment]
That's a fascinating problem, thanks for submitting it!

I only skimmed the code example you sent, and I can't see any obvious problems with it - so that might indeed be a governor bug. I'll check it out in detail tonight.

**Comment by antifuchs** [comment]
Ah! Phew! OK, there *was* a problem in the example you sent, after all. It's subtle!

The async code increments `i` only when the rate limiter allows the next cell through: `until_ready` does not resolve until there is a positive result from the rate limiter. That is, it sleeps, then checks if it can go, and if not, it sleeps again.

However, the sync code you sent increments `i` every time through the loop, and sleeps without re-checking after sleeping.

With this updated function:
```rust
fn sync(polling_rate: u32) {
    let clock = clock::DefaultClock::default();
    let limiter = RateLimiter::direct_with_clock(
        Quota::per_second(NonZeroU32::new(polling_rate).unwrap())
                .allow_burst(NonZeroU32::new(1u32).unwrap()),
        &clock
    );

    let mut i = 0;
    let mut last = Instant::now();
    let interval = Duration::from_secs(1);
    loop {
        let now = Instant::now();
        if now > last + interval {
            println!("[Sync] Count: {}", i);
            i = 0;
            last = now;
        }

        if let Err(negative) = limiter.check() {
            thread::sleep(negative.wait_time_from(clock.now()));
        } else {
            i = i + 1;
        }
    }
}
```

The values if `i` sync up correctly. My suspicion is that the times returned by the limiter don't match exactly the time being slept by sleep, which means it would go like this:

1. increment i
2. check -> allowed
3. increment i
4. check -> denied
5. sleep
6. increment i (wrongly)
7. check -> allowed
8. increment i

And so on - which increments i one more time than the rate limiter allows. Compare with the updated code:

1. check -> allowed
2. increment i
3. check -> denied
4. sleep
5. check -> allowed
6. increment i

...which increments only when the limiter allows it.

Hope that makes sense!

**Comment by LAGonauta** [comment]
Oh, I am very sorry for this noise!
I really thought that something was up. I feel bad for it now...
[This change](https://github.com/LAGonauta/RustHIDtoVPADNetworkClient/commit/8548161f6e675443021b83f1fbdabf0ff6f6e5eb) fixed it for me on my codebase, thank you very much!

**Comment by antifuchs** [comment]
Don't worry - it's good to see where people are hitting walls in understanding what's going on, so it can improve! I suspect that #67 might be helpful for your use case (where it'll let you increment a counter on a positive decision), once it lands.
