### ISSUE TITLE
Unclear how to store RateLimiter in struct

### ISSUE THREAD

**Issue by dbr** [antifuchs/governor#85]
Minor thing I encountered while updating a small project from `rate_limiter` to `governor`. It's using it in a very basic way, but roughly like:

```rust
struct Example {
    rate_limit: DirectRateLimiter<GCRA>,
}
```

However on first glance, it's not clear how to go from the example in the governor docs:
```
use std::num::NonZeroU32;
use nonzero_ext::*;
use governor::{Quota, RateLimiter};

let mut lim = RateLimiter::direct(Quota::per_second(nonzero!(50u32))); // Allow 50 units per second
assert_eq!(Ok(()), lim.check());
```

to something along these lines:

```
use std::num::NonZeroU32;
use nonzero_ext::*;
use governor::{Quota, RateLimiter};

struct Example {
    limiter: RateLimiter<???>,
}

let eg = Example {
    limiter: RateLimiter::direct(Quota::per_second(nonzero!(50u32))),
}
assert_eq!(Ok(()), eg.limiter.check()); // although these are in methods on Example
```

All the examples I could find just create the limiter in a function (so just simple `let x = ` binding), and working out the generic parameters is slightly unclear

Is this an "expected" use of the API, or is there a more conventional approach which avoids needing to specify the generic parameters?

**Comment by antifuchs** [comment]
Hi, thanks for your interest! How to store a rate limiter in structs is definitely a thing that the docs ought to cover better, right on the cover page. Also, the types aren't super ergonomic for people that can't rely on type inference at the moment - even if you only use the defaults, as a person putting rate limiters on structs, you have to type out all the type args and that's tedious.

To answer your question specifically, I think I need to start with the type signature you're trying to form: It's not the way a governor RateLimiter should look - it looks like one from `ratelimit_meter` (the preceding crate, which had many design flaws, one of them being that type signature)! The concrete RateLimiter type signature is this:

`RateLimiter<KeyType, StateStore, Clock>`

A direct rate limiter that uses the default real-time clock would have this type signature:

`RateLimiter<NotKeyed, InMemoryState, DefaultClock>` - you can find that signature in the docs for to the return type of [`RateLimiter::direct`](https://docs.rs/governor/0.3.2/governor/struct.RateLimiter.html#method.direct). 

Now, I should also note that in the next release, 0.4.x, there'll be a new generic parameter with a default, which will still require that your struct type sig changes; I will leave this issue open to ensure the next release has a more convenient type definition that remains backwards-compatible (and doesn't require people to spend ages digging through docs!)

Hope that helps!

**Comment by antifuchs** [comment]
> I don't get autocomplete for the RateLimiter constructor like methods besides of new.

That's curious (but may be related to the near-extreme levels of genericness going on)... are you using rust-analyzer? What version? With rust-analyzer 2021-09-06, I get the following:

<img width="2189" alt="Screen Shot 2021-09-11 at 11 09 35" src="https://user-images.githubusercontent.com/11864/132952453-3cffddc7-1992-46ac-a2ef-53574226256d.png">

**Comment by gitmalong** [comment]
Switching my vscode extension from rust to rust-analyzer made the autocomplete work! Thanks!

**Comment by antifuchs** [comment]
The next release, 0.6.0, will have `DefaultKeyedRateLimiter` and `DefaultDirectRateLimiter` type aliases. Hope they will cut down on the type typing we have to do!
