### ISSUE TITLE
Queues

### ISSUE THREAD

**Issue by gitmalong** [antifuchs/governor#94]
Is there something on top of governor that allows queuing of callbacks similar to https://www.npmjs.com/package/bottleneck ?

**Comment by antifuchs** [comment]
Good question - I don't think we'll build this into governor directly, but the [`async` "until" functions](https://docs.rs/governor/0.3.2/governor/struct.RateLimiter.html#direct-rate-limiters---asyncawait) combine with the underlying async runtime to allow rate-limiting of tasks, very much like a queue processor would do it. The main difficulty is that governor is built to be in-memory only, so far: you won't be able to use Redis as a rate-limiting information storage without some pain.

So: I can see somebody building an async task-processing library based on this. It probably should be a different crate, though.

Hope that answers your question - feel free to reopen if there's anything else you think I didn't answer.
